#ifndef IOAPI_IMPL_IO_CFG_H_INCLUDED
#define IOAPI_IMPL_IO_CFG_H_INCLUDED

#define IOAPI_CHECKED_BUILD

#define IOAPI_DEVICE_COUNT_MAX (127-1)

#define IOAPI_CTL
#define IOAPI_SYNC
#define IOAPI_ASYNC
#define IOAPI_EVENT

#endif /* IOAPI_IMPL_IO_CFG_H_INCLUDED */
